#!/bin/bash
echo "1.  Currently logged users"
echo "2.  Your shell directory"
echo "3.  Home directory"
echo "4.  OS name & version"
echo "5.  Current working directory"
echo "6.  Number of users logged in"
echo "7.  Show all available shells in your system"
echo "8.  Hard disk information"
echo "9.  CPU information"
echo "10. Memory information"
echo "11. File system information"
echo "12. Currently running process"
echo "Choose your option: 10"
echo "Memory Info:"
free
echo "Continue (y/n) :y"
echo "Sys Info:"
echo "1.  Currently logged users"
echo "2.  Your shell directory"
echo "3.  Home directory"
echo "4.  OS name & version"
echo "5.  Current working directory"
echo "6.  Number of users logged in"
echo "7.  Show all available shells in your system"
echo "8.  Hard disk information"
echo "9.  CPU information"
echo "10. Memory information"
echo "11. File system information"
echo "12. Currently running process"
echo "Choose your option: 10"
echo "Choose your option: 4"
echo " Os Info:"
w
echo "Continue (y/n) :n"
